### ISSUE TITLE
JSX conformance spec checklist

### ISSUE THREAD

**Issue by RyanCavanaugh** [RyanCavanaugh/TypeScript#1]
[ ] Given an expression of the form `<N />`, where `N` is any identifier or dotted identifier:
- [x] Attempt intrinsic lookup:
  - [x] Intrinsic lookup fails if the `JSX.IntrinsicElements` type does not exist
  - [x] Determine `A`, the _element attributes type_:
    - [x] If the property named `N` exists in the type `JSX.IntrinsicElements`, `A` is the type of that property
    - [x] If `JSX.InstrinsicElements` has a string indexer, `A` is the type of that indexer
  - Otherwise instrinsic lookup fails
- [x] If intrinsic lookup failed:
  - [x] Look up the value `N`.
    - [x] Error if no value named `N` exists in the current scope
    - [x] N.B. dotted names
  - [x] `C`, the _element class type_, is the type of the value `N`
  - [x] Determine `E`, the _element instance type_:
    - [x] If `C` is `any`, `E` is `any`
    - [x] Otherwise, `E` is:
      - [x] The union type of the return types of `C`'s construct signatures, if `C` has at least 1 construct signature
      - [x] The union type of the return types of `C`'s call signatures, if `C` has at least 1 call signature and no construct signatures
      - [x] An error is issued if `C` has no call or construct signatures
  - [x] Error if `E` is not an object type and is not `any`
  - [x] If the type `JSX.ElementClass` exists, check that `E` is assignable to `JSX.ElementClass`
  - [x] Determine `A`, the _element attributes type_:
    - [x] If `E` is `any`, `A` is `any`
    - [x] If the type `JSX.ElementAttributesProperty` does not exist, `A` is `any`
    - [x] If `JSX.ElementAttributesProperty` has 0 properties, `A` is `E`
    - [x] If `JSX.ElementAttributesProperty` has 1 property `P` and `E` has a property `P`, `A` is the type of `E.P`
    - [x] If `JSX.ElementAttributesProperty` has 1 property `P` and `E` does not have a property `P`, `A` is `void`
    - [x] If `JSX.ElementAttributesProperty` has more than 1 property, issue an error
- [x] The type of the expression is `JSX.Element`
  - [x] It is an error if the type `JSX.Element` does not exist

`<foo x={y} {...s} />`
- [x] Let `A` be the _element attributes type_ derived from `foo`
- [x] Process the attributes in right to left order:
  - [x] If `A` is `void`, issue an error
  - [x] If the attribute is a non-spread attribute named `P` initialized with an expression `e`:
    - [x] If `A` has a property `P`:
      - [x] Process `e` with the contextual type of the type of `A.P`.
    - [x] It is an error if `e` is not assignable to `A.P`.
    - [x] If `A` does not have a property `P`:
      - [x] Process `e` without a contextual type
    - [x] If the name of `P` is a valid JavaScript identifier, issue an error
    - [x] If the name of `P` is an invalid JavaScript identifier because it is a reserved word, issue an error
  - [x] If the attribute is a spread attribute initialized with an expression `e`:
    - [x] Process `e` with the contextual type `A`
    - [x] For each property `P` in the apparent type of `e`:
      - [x] If an attribute assignment with the name `P` has already occurred (either as an explicit attribute or as part of another spread attribute) in the containing element, nothing happens
      - [x] Otherwise, if `A` has a property `P`:
        - [x] It is an error if `e.P` is not assignable to `A.P`.
- [x] After all attributes have been processed, issue an error if any required property in `A` does not have a corresponding attribute or property of a spread attribute
